// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadContacts = `-- name: CountUnreadContacts :one
SELECT COUNT(*) FROM contact_submissions WHERE read = false
`

func (q *Queries) CountUnreadContacts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadContacts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContactSubmission = `-- name: CreateContactSubmission :one
INSERT INTO contact_submissions (name, email, phone, subject, message)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, phone, subject, message, read, created_at
`

type CreateContactSubmissionParams struct {
	Name    string      `json:"name"`
	Email   string      `json:"email"`
	Phone   pgtype.Text `json:"phone"`
	Subject pgtype.Text `json:"subject"`
	Message string      `json:"message"`
}

func (q *Queries) CreateContactSubmission(ctx context.Context, arg CreateContactSubmissionParams) (ContactSubmission, error) {
	row := q.db.QueryRow(ctx, createContactSubmission,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Subject,
		arg.Message,
	)
	var i ContactSubmission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Subject,
		&i.Message,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContactSubmission = `-- name: DeleteContactSubmission :exec
DELETE FROM contact_submissions WHERE id = $1
`

func (q *Queries) DeleteContactSubmission(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteContactSubmission, id)
	return err
}

const getContactSubmission = `-- name: GetContactSubmission :one
SELECT id, name, email, phone, subject, message, read, created_at FROM contact_submissions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetContactSubmission(ctx context.Context, id int32) (ContactSubmission, error) {
	row := q.db.QueryRow(ctx, getContactSubmission, id)
	var i ContactSubmission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Subject,
		&i.Message,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const listContactSubmissions = `-- name: ListContactSubmissions :many
SELECT id, name, email, phone, subject, message, read, created_at FROM contact_submissions ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListContactSubmissionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListContactSubmissions(ctx context.Context, arg ListContactSubmissionsParams) ([]ContactSubmission, error) {
	rows, err := q.db.Query(ctx, listContactSubmissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactSubmission{}
	for rows.Next() {
		var i ContactSubmission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Subject,
			&i.Message,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadContactSubmissions = `-- name: ListUnreadContactSubmissions :many
SELECT id, name, email, phone, subject, message, read, created_at FROM contact_submissions WHERE read = false ORDER BY created_at DESC
`

func (q *Queries) ListUnreadContactSubmissions(ctx context.Context) ([]ContactSubmission, error) {
	rows, err := q.db.Query(ctx, listUnreadContactSubmissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactSubmission{}
	for rows.Next() {
		var i ContactSubmission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Subject,
			&i.Message,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markContactRead = `-- name: MarkContactRead :exec
UPDATE contact_submissions SET read = true WHERE id = $1
`

func (q *Queries) MarkContactRead(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markContactRead, id)
	return err
}
