// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrders = `-- name: CountOrders :one
SELECT COUNT(*) FROM orders
`

func (q *Queries) CountOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdersByStatus = `-- name: CountOrdersByStatus :one
SELECT COUNT(*) FROM orders WHERE status = $1
`

func (q *Queries) CountOrdersByStatus(ctx context.Context, status pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (stripe_session_id, customer_email, customer_name, customer_phone, shipping_address, items, subtotal_cents, shipping_cents, total_cents, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, stripe_session_id, stripe_payment_intent, customer_email, customer_name, customer_phone, shipping_address, items, subtotal_cents, shipping_cents, total_cents, status, notes, created_at, updated_at
`

type CreateOrderParams struct {
	StripeSessionID pgtype.Text `json:"stripe_session_id"`
	CustomerEmail   string      `json:"customer_email"`
	CustomerName    pgtype.Text `json:"customer_name"`
	CustomerPhone   pgtype.Text `json:"customer_phone"`
	ShippingAddress pgtype.Text `json:"shipping_address"`
	Items           string      `json:"items"`
	SubtotalCents   int32       `json:"subtotal_cents"`
	ShippingCents   pgtype.Int4 `json:"shipping_cents"`
	TotalCents      int32       `json:"total_cents"`
	Status          pgtype.Text `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.StripeSessionID,
		arg.CustomerEmail,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.ShippingAddress,
		arg.Items,
		arg.SubtotalCents,
		arg.ShippingCents,
		arg.TotalCents,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.StripeSessionID,
		&i.StripePaymentIntent,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.ShippingAddress,
		&i.Items,
		&i.SubtotalCents,
		&i.ShippingCents,
		&i.TotalCents,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, stripe_session_id, stripe_payment_intent, customer_email, customer_name, customer_phone, shipping_address, items, subtotal_cents, shipping_cents, total_cents, status, notes, created_at, updated_at FROM orders WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id int32) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.StripeSessionID,
		&i.StripePaymentIntent,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.ShippingAddress,
		&i.Items,
		&i.SubtotalCents,
		&i.ShippingCents,
		&i.TotalCents,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByStripeSession = `-- name: GetOrderByStripeSession :one
SELECT id, stripe_session_id, stripe_payment_intent, customer_email, customer_name, customer_phone, shipping_address, items, subtotal_cents, shipping_cents, total_cents, status, notes, created_at, updated_at FROM orders WHERE stripe_session_id = $1 LIMIT 1
`

func (q *Queries) GetOrderByStripeSession(ctx context.Context, stripeSessionID pgtype.Text) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByStripeSession, stripeSessionID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.StripeSessionID,
		&i.StripePaymentIntent,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.ShippingAddress,
		&i.Items,
		&i.SubtotalCents,
		&i.ShippingCents,
		&i.TotalCents,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecentOrders = `-- name: GetRecentOrders :many
SELECT id, stripe_session_id, stripe_payment_intent, customer_email, customer_name, customer_phone, shipping_address, items, subtotal_cents, shipping_cents, total_cents, status, notes, created_at, updated_at FROM orders ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) GetRecentOrders(ctx context.Context, limit int32) ([]Order, error) {
	rows, err := q.db.Query(ctx, getRecentOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.StripeSessionID,
			&i.StripePaymentIntent,
			&i.CustomerEmail,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.ShippingAddress,
			&i.Items,
			&i.SubtotalCents,
			&i.ShippingCents,
			&i.TotalCents,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, stripe_session_id, stripe_payment_intent, customer_email, customer_name, customer_phone, shipping_address, items, subtotal_cents, shipping_cents, total_cents, status, notes, created_at, updated_at FROM orders ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListOrdersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.StripeSessionID,
			&i.StripePaymentIntent,
			&i.CustomerEmail,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.ShippingAddress,
			&i.Items,
			&i.SubtotalCents,
			&i.ShippingCents,
			&i.TotalCents,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByEmail = `-- name: ListOrdersByEmail :many
SELECT id, stripe_session_id, stripe_payment_intent, customer_email, customer_name, customer_phone, shipping_address, items, subtotal_cents, shipping_cents, total_cents, status, notes, created_at, updated_at FROM orders WHERE customer_email = $1 ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByEmail(ctx context.Context, customerEmail string) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByEmail, customerEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.StripeSessionID,
			&i.StripePaymentIntent,
			&i.CustomerEmail,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.ShippingAddress,
			&i.Items,
			&i.SubtotalCents,
			&i.ShippingCents,
			&i.TotalCents,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByStatus = `-- name: ListOrdersByStatus :many
SELECT id, stripe_session_id, stripe_payment_intent, customer_email, customer_name, customer_phone, shipping_address, items, subtotal_cents, shipping_cents, total_cents, status, notes, created_at, updated_at FROM orders WHERE status = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListOrdersByStatusParams struct {
	Status pgtype.Text `json:"status"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListOrdersByStatus(ctx context.Context, arg ListOrdersByStatusParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.StripeSessionID,
			&i.StripePaymentIntent,
			&i.CustomerEmail,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.ShippingAddress,
			&i.Items,
			&i.SubtotalCents,
			&i.ShippingCents,
			&i.TotalCents,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderPaymentIntent = `-- name: UpdateOrderPaymentIntent :exec
UPDATE orders
SET stripe_payment_intent = $1, updated_at = CURRENT_TIMESTAMP
WHERE stripe_session_id = $2
`

type UpdateOrderPaymentIntentParams struct {
	StripePaymentIntent pgtype.Text `json:"stripe_payment_intent"`
	StripeSessionID     pgtype.Text `json:"stripe_session_id"`
}

func (q *Queries) UpdateOrderPaymentIntent(ctx context.Context, arg UpdateOrderPaymentIntentParams) error {
	_, err := q.db.Exec(ctx, updateOrderPaymentIntent, arg.StripePaymentIntent, arg.StripeSessionID)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateOrderStatusParams struct {
	Status pgtype.Text `json:"status"`
	ID     int32       `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.Status, arg.ID)
	return err
}

const updateOrderStatusBySession = `-- name: UpdateOrderStatusBySession :exec
UPDATE orders
SET status = $1, updated_at = CURRENT_TIMESTAMP
WHERE stripe_session_id = $2
`

type UpdateOrderStatusBySessionParams struct {
	Status          pgtype.Text `json:"status"`
	StripeSessionID pgtype.Text `json:"stripe_session_id"`
}

func (q *Queries) UpdateOrderStatusBySession(ctx context.Context, arg UpdateOrderStatusBySessionParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatusBySession, arg.Status, arg.StripeSessionID)
	return err
}
