// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: testimonials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTestimonial = `-- name: CreateTestimonial :one
INSERT INTO testimonials (author, location, content, rating, featured)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, author, location, content, rating, featured, created_at
`

type CreateTestimonialParams struct {
	Author   string      `json:"author"`
	Location pgtype.Text `json:"location"`
	Content  string      `json:"content"`
	Rating   pgtype.Int4 `json:"rating"`
	Featured pgtype.Bool `json:"featured"`
}

func (q *Queries) CreateTestimonial(ctx context.Context, arg CreateTestimonialParams) (Testimonial, error) {
	row := q.db.QueryRow(ctx, createTestimonial,
		arg.Author,
		arg.Location,
		arg.Content,
		arg.Rating,
		arg.Featured,
	)
	var i Testimonial
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Location,
		&i.Content,
		&i.Rating,
		&i.Featured,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTestimonial = `-- name: DeleteTestimonial :exec
DELETE FROM testimonials WHERE id = $1
`

func (q *Queries) DeleteTestimonial(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTestimonial, id)
	return err
}

const getTestimonial = `-- name: GetTestimonial :one
SELECT id, author, location, content, rating, featured, created_at FROM testimonials WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTestimonial(ctx context.Context, id int32) (Testimonial, error) {
	row := q.db.QueryRow(ctx, getTestimonial, id)
	var i Testimonial
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Location,
		&i.Content,
		&i.Rating,
		&i.Featured,
		&i.CreatedAt,
	)
	return i, err
}

const listFeaturedTestimonials = `-- name: ListFeaturedTestimonials :many
SELECT id, author, location, content, rating, featured, created_at FROM testimonials WHERE featured = true ORDER BY created_at DESC
`

func (q *Queries) ListFeaturedTestimonials(ctx context.Context) ([]Testimonial, error) {
	rows, err := q.db.Query(ctx, listFeaturedTestimonials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Testimonial{}
	for rows.Next() {
		var i Testimonial
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Location,
			&i.Content,
			&i.Rating,
			&i.Featured,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestimonials = `-- name: ListTestimonials :many
SELECT id, author, location, content, rating, featured, created_at FROM testimonials ORDER BY created_at DESC
`

func (q *Queries) ListTestimonials(ctx context.Context) ([]Testimonial, error) {
	rows, err := q.db.Query(ctx, listTestimonials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Testimonial{}
	for rows.Next() {
		var i Testimonial
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Location,
			&i.Content,
			&i.Rating,
			&i.Featured,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTestimonial = `-- name: UpdateTestimonial :exec
UPDATE testimonials
SET author = $1, location = $2, content = $3, rating = $4, featured = $5
WHERE id = $6
`

type UpdateTestimonialParams struct {
	Author   string      `json:"author"`
	Location pgtype.Text `json:"location"`
	Content  string      `json:"content"`
	Rating   pgtype.Int4 `json:"rating"`
	Featured pgtype.Bool `json:"featured"`
	ID       int32       `json:"id"`
}

func (q *Queries) UpdateTestimonial(ctx context.Context, arg UpdateTestimonialParams) error {
	_, err := q.db.Exec(ctx, updateTestimonial,
		arg.Author,
		arg.Location,
		arg.Content,
		arg.Rating,
		arg.Featured,
		arg.ID,
	)
	return err
}
