// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hero_slides.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHeroSlide = `-- name: CreateHeroSlide :one
INSERT INTO hero_slides (image, alt_text, sort_order, active)
VALUES ($1, $2, $3, $4)
RETURNING id, image, alt_text, sort_order, active
`

type CreateHeroSlideParams struct {
	Image     string      `json:"image"`
	AltText   pgtype.Text `json:"alt_text"`
	SortOrder pgtype.Int4 `json:"sort_order"`
	Active    pgtype.Bool `json:"active"`
}

func (q *Queries) CreateHeroSlide(ctx context.Context, arg CreateHeroSlideParams) (HeroSlide, error) {
	row := q.db.QueryRow(ctx, createHeroSlide,
		arg.Image,
		arg.AltText,
		arg.SortOrder,
		arg.Active,
	)
	var i HeroSlide
	err := row.Scan(
		&i.ID,
		&i.Image,
		&i.AltText,
		&i.SortOrder,
		&i.Active,
	)
	return i, err
}

const deleteHeroSlide = `-- name: DeleteHeroSlide :exec
DELETE FROM hero_slides WHERE id = $1
`

func (q *Queries) DeleteHeroSlide(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteHeroSlide, id)
	return err
}

const getHeroSlide = `-- name: GetHeroSlide :one
SELECT id, image, alt_text, sort_order, active FROM hero_slides WHERE id = $1 LIMIT 1
`

func (q *Queries) GetHeroSlide(ctx context.Context, id int32) (HeroSlide, error) {
	row := q.db.QueryRow(ctx, getHeroSlide, id)
	var i HeroSlide
	err := row.Scan(
		&i.ID,
		&i.Image,
		&i.AltText,
		&i.SortOrder,
		&i.Active,
	)
	return i, err
}

const listActiveHeroSlides = `-- name: ListActiveHeroSlides :many
SELECT id, image, alt_text, sort_order, active FROM hero_slides WHERE active = true ORDER BY sort_order
`

func (q *Queries) ListActiveHeroSlides(ctx context.Context) ([]HeroSlide, error) {
	rows, err := q.db.Query(ctx, listActiveHeroSlides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeroSlide{}
	for rows.Next() {
		var i HeroSlide
		if err := rows.Scan(
			&i.ID,
			&i.Image,
			&i.AltText,
			&i.SortOrder,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeroSlides = `-- name: ListHeroSlides :many
SELECT id, image, alt_text, sort_order, active FROM hero_slides ORDER BY sort_order
`

func (q *Queries) ListHeroSlides(ctx context.Context) ([]HeroSlide, error) {
	rows, err := q.db.Query(ctx, listHeroSlides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeroSlide{}
	for rows.Next() {
		var i HeroSlide
		if err := rows.Scan(
			&i.ID,
			&i.Image,
			&i.AltText,
			&i.SortOrder,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHeroSlide = `-- name: UpdateHeroSlide :exec
UPDATE hero_slides
SET image = $1, alt_text = $2, sort_order = $3, active = $4
WHERE id = $5
`

type UpdateHeroSlideParams struct {
	Image     string      `json:"image"`
	AltText   pgtype.Text `json:"alt_text"`
	SortOrder pgtype.Int4 `json:"sort_order"`
	Active    pgtype.Bool `json:"active"`
	ID        int32       `json:"id"`
}

func (q *Queries) UpdateHeroSlide(ctx context.Context, arg UpdateHeroSlideParams) error {
	_, err := q.db.Exec(ctx, updateHeroSlide,
		arg.Image,
		arg.AltText,
		arg.SortOrder,
		arg.Active,
		arg.ID,
	)
	return err
}
