// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	SortOrder   pgtype.Int4 `json:"sort_order"`
}

type ContactSubmission struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	Subject   pgtype.Text        `json:"subject"`
	Message   string             `json:"message"`
	Read      pgtype.Bool        `json:"read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type HeroSlide struct {
	ID        int32       `json:"id"`
	Image     string      `json:"image"`
	AltText   pgtype.Text `json:"alt_text"`
	SortOrder pgtype.Int4 `json:"sort_order"`
	Active    pgtype.Bool `json:"active"`
}

type Order struct {
	ID                  int32              `json:"id"`
	StripeSessionID     pgtype.Text        `json:"stripe_session_id"`
	StripePaymentIntent pgtype.Text        `json:"stripe_payment_intent"`
	CustomerEmail       string             `json:"customer_email"`
	CustomerName        pgtype.Text        `json:"customer_name"`
	CustomerPhone       pgtype.Text        `json:"customer_phone"`
	ShippingAddress     pgtype.Text        `json:"shipping_address"`
	Items               string             `json:"items"`
	SubtotalCents       int32              `json:"subtotal_cents"`
	ShippingCents       pgtype.Int4        `json:"shipping_cents"`
	TotalCents          int32              `json:"total_cents"`
	Status              pgtype.Text        `json:"status"`
	Notes               pgtype.Text        `json:"notes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID          int32              `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	CategoryID  pgtype.Text        `json:"category_id"`
	PriceCents  int32              `json:"price_cents"`
	Weight      pgtype.Text        `json:"weight"`
	Description pgtype.Text        `json:"description"`
	Image       pgtype.Text        `json:"image"`
	Featured    pgtype.Bool        `json:"featured"`
	InStock     pgtype.Bool        `json:"in_stock"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SiteSetting struct {
	Key       string             `json:"key"`
	Value     pgtype.Text        `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Testimonial struct {
	ID        int32              `json:"id"`
	Author    string             `json:"author"`
	Location  pgtype.Text        `json:"location"`
	Content   string             `json:"content"`
	Rating    pgtype.Int4        `json:"rating"`
	Featured  pgtype.Bool        `json:"featured"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
