// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsByCategory = `-- name: CountProductsByCategory :one
SELECT COUNT(*) FROM products WHERE category_id = $1
`

func (q *Queries) CountProductsByCategory(ctx context.Context, categoryID pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (slug, name, category_id, price_cents, weight, description, image, featured, in_stock)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, slug, name, category_id, price_cents, weight, description, image, featured, in_stock, created_at, updated_at
`

type CreateProductParams struct {
	Slug        string      `json:"slug"`
	Name        string      `json:"name"`
	CategoryID  pgtype.Text `json:"category_id"`
	PriceCents  int32       `json:"price_cents"`
	Weight      pgtype.Text `json:"weight"`
	Description pgtype.Text `json:"description"`
	Image       pgtype.Text `json:"image"`
	Featured    pgtype.Bool `json:"featured"`
	InStock     pgtype.Bool `json:"in_stock"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Slug,
		arg.Name,
		arg.CategoryID,
		arg.PriceCents,
		arg.Weight,
		arg.Description,
		arg.Image,
		arg.Featured,
		arg.InStock,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CategoryID,
		&i.PriceCents,
		&i.Weight,
		&i.Description,
		&i.Image,
		&i.Featured,
		&i.InStock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const deleteProductBySlug = `-- name: DeleteProductBySlug :exec
DELETE FROM products WHERE slug = $1
`

func (q *Queries) DeleteProductBySlug(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteProductBySlug, slug)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, slug, name, category_id, price_cents, weight, description, image, featured, in_stock, created_at, updated_at FROM products WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CategoryID,
		&i.PriceCents,
		&i.Weight,
		&i.Description,
		&i.Image,
		&i.Featured,
		&i.InStock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, slug, name, category_id, price_cents, weight, description, image, featured, in_stock, created_at, updated_at FROM products WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CategoryID,
		&i.PriceCents,
		&i.Weight,
		&i.Description,
		&i.Image,
		&i.Featured,
		&i.InStock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeaturedProducts = `-- name: ListFeaturedProducts :many
SELECT id, slug, name, category_id, price_cents, weight, description, image, featured, in_stock, created_at, updated_at FROM products WHERE featured = true ORDER BY name
`

func (q *Queries) ListFeaturedProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listFeaturedProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CategoryID,
			&i.PriceCents,
			&i.Weight,
			&i.Description,
			&i.Image,
			&i.Featured,
			&i.InStock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInStockProducts = `-- name: ListInStockProducts :many
SELECT id, slug, name, category_id, price_cents, weight, description, image, featured, in_stock, created_at, updated_at FROM products WHERE in_stock = true ORDER BY name
`

func (q *Queries) ListInStockProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listInStockProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CategoryID,
			&i.PriceCents,
			&i.Weight,
			&i.Description,
			&i.Image,
			&i.Featured,
			&i.InStock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, slug, name, category_id, price_cents, weight, description, image, featured, in_stock, created_at, updated_at FROM products ORDER BY name
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CategoryID,
			&i.PriceCents,
			&i.Weight,
			&i.Description,
			&i.Image,
			&i.Featured,
			&i.InStock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT id, slug, name, category_id, price_cents, weight, description, image, featured, in_stock, created_at, updated_at FROM products WHERE category_id = $1 ORDER BY name
`

func (q *Queries) ListProductsByCategory(ctx context.Context, categoryID pgtype.Text) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CategoryID,
			&i.PriceCents,
			&i.Weight,
			&i.Description,
			&i.Image,
			&i.Featured,
			&i.InStock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, slug, name, category_id, price_cents, weight, description, image, featured, in_stock, created_at, updated_at FROM products
WHERE name LIKE $1 OR description LIKE $2
ORDER BY name
`

type SearchProductsParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, searchProducts, arg.Name, arg.Description)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CategoryID,
			&i.PriceCents,
			&i.Weight,
			&i.Description,
			&i.Image,
			&i.Featured,
			&i.InStock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET name = $1, category_id = $2, price_cents = $3, weight = $4, description = $5, image = $6, featured = $7, in_stock = $8, updated_at = CURRENT_TIMESTAMP
WHERE id = $9
`

type UpdateProductParams struct {
	Name        string      `json:"name"`
	CategoryID  pgtype.Text `json:"category_id"`
	PriceCents  int32       `json:"price_cents"`
	Weight      pgtype.Text `json:"weight"`
	Description pgtype.Text `json:"description"`
	Image       pgtype.Text `json:"image"`
	Featured    pgtype.Bool `json:"featured"`
	InStock     pgtype.Bool `json:"in_stock"`
	ID          int32       `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.Name,
		arg.CategoryID,
		arg.PriceCents,
		arg.Weight,
		arg.Description,
		arg.Image,
		arg.Featured,
		arg.InStock,
		arg.ID,
	)
	return err
}

const updateProductBySlug = `-- name: UpdateProductBySlug :exec
UPDATE products
SET name = $1, category_id = $2, price_cents = $3, weight = $4, description = $5, image = $6, featured = $7, in_stock = $8, updated_at = CURRENT_TIMESTAMP
WHERE slug = $9
`

type UpdateProductBySlugParams struct {
	Name        string      `json:"name"`
	CategoryID  pgtype.Text `json:"category_id"`
	PriceCents  int32       `json:"price_cents"`
	Weight      pgtype.Text `json:"weight"`
	Description pgtype.Text `json:"description"`
	Image       pgtype.Text `json:"image"`
	Featured    pgtype.Bool `json:"featured"`
	InStock     pgtype.Bool `json:"in_stock"`
	Slug        string      `json:"slug"`
}

func (q *Queries) UpdateProductBySlug(ctx context.Context, arg UpdateProductBySlugParams) error {
	_, err := q.db.Exec(ctx, updateProductBySlug,
		arg.Name,
		arg.CategoryID,
		arg.PriceCents,
		arg.Weight,
		arg.Description,
		arg.Image,
		arg.Featured,
		arg.InStock,
		arg.Slug,
	)
	return err
}
